import type { NextPage } from 'next'
import Head from 'next/head'
import tw from 'twin.macro'
import styled from 'styled-components'

const Home: NextPage = () => {
  return (
    <MainContainer>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <span>Hello</span>
    </MainContainer>
  )
}

const MainContainer = styled.div`
  ${tw`
    text-red-400
  `}
`

export default Home
